# Jour 10 - 24 Juillet 2026 : Manipulation de Données avec Pandas

**Pandas** est l'outil incontournable pour analyser des données tabulaires (comme des fichiers Excel ou CSV). Il utilise deux structures principales : les **Series** (1 colonne) et les **DataFrames** (un tableau avec des lignes et des colonnes).

In [1]:
import pandas as pd

# Création d'un DataFrame (tableau) à partir d'un dictionnaire
donnees = {
    'Nom': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Ville': ['Paris', 'Lyon', 'Marseille']
}

df = pd.DataFrame(donnees)
df

       Nom  Age      Ville
0    Alice   25      Paris
1      Bob   30       Lyon
2  Charlie   35  Marseille

## Sélection de données
On peut sélectionner une seule colonne avec `df['NomColonne']` ou plusieurs avec une liste de colonnes.

In [2]:
# Sélectionner seulement la colonne Age
print(df['Age'])

# Filtrer les personnes de plus de 28 ans
plus_de_28 = df[df['Age'] > 28]
plus_de_28

0    25
1    30
2    35
Name: Age, dtype: int64

       Nom  Age      Ville
1      Bob   30       Lyon
2  Charlie   35  Marseille

---
## 🏆 Défi du Jour 10

1. Créez un DataFrame `df_employes` contenant 3 employés avec les colonnes : `Nom`, `Salaire`, et `Service`.
2. Affichez uniquement la colonne `Salaire`.
3. Filtrez et affichez uniquement les employés qui gagnent plus de 2500 (inventez les valeurs pour que le filtre fonctionne).

In [3]:
import pandas as pd

# 1. Création du DataFrame df_employes
donnees_employes = {
    'Nom': ['Awa', 'Moussa', 'Fatou'],
    'Salaire': [2200, 3000, 2700],
    'Service': ['Marketing', 'IT', 'RH']
}
df_employes = pd.DataFrame(donnees_employes)
print(df_employes)

# 2. Affichage uniquement de la colonne Salaire
print("\nColonne Salaire :")
print(df_employes['Salaire'])

# 3. Filtrage des employés gagnant plus de 2500
plus_de_2500 = df_employes[df_employes['Salaire'] > 2500]
print("\nEmployés gagnant plus de 2500 :")
print(plus_de_2500)

      Nom  Salaire    Service
0     Awa     2200  Marketing
1  Moussa     3000         IT
2   Fatou     2700         RH

Colonne Salaire :
0    2200
1    3000
2    2700
Name: Salaire, dtype: int64

Employés gagnant plus de 2500 :
      Nom  Salaire Service
1  Moussa     3000      IT
2   Fatou     2700      RH